const romanFromArabic = (arabic) => String.prototype.repeat.call('I', arabic)
	.replace(/IIIII/g, 'V')
	.replace(/VV/g, 'X')
	.replace(/XXXXX/g, 'L')
	.replace(/LL/g, 'C')
	.replace(/CCCCC/g, 'D')
	.replace(/DD/g, 'M')
	.replace(/IIII/g, 'IV')
	.replace(/VIV/g, 'IX')
	.replace(/XXXX/g, 'XL')
	.replace(/LXL/g, 'XC')
	.replace(/CCCC/g, 'CD')
	.replace(/DCD/g, 'CM')
;
module.exports = romanFromArabic;